

services:
  hri_cacti_s:
    extends:
      file: Docker/docker-compose.yaml
      service: hri_cacti_s

  ros_bridge:
    extends:
      file: Docker/ros_bridge/compose.yaml
      service: ros_bridge
      profile: bridge
